# Generated by Django 2.2.7 on 2020-04-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_illness_medicalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalinfo',
            options={'verbose_name_plural': 'Medical Information'},
        ),
        migrations.RenameField(
            model_name='medicalinfo',
            old_name='name',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='weight',
        ),
    ]
